### ISSUE TITLE
Problem with sentences with coma or other symbols

### ISSUE THREAD

**Issue by Gene111** [DrewSSP/bulk-audio-upload#1]
Hi, I've been trying to use your code to upload audio files for german course. 
At first words with spaces (e.g. "das Wasser") couldn't be uploaded. 
Than I changed 
`temp_file = download_audio('http://soundoftext.com/static/sounds/de/' + audio['chinese_word'] + '.mp3') `
to 
`temp_file = download_audio('http://soundoftext.com/static/sounds/de/' + audio['chinese_word'].replace(' ', '_') + '.mp3') `
Which did the job for words with spaces but words or sentences with other symbols still doesn't work.

I tried to encode it with
`from requests.utils import quote
`
```
def sequence_through_audios(audios):
	for audio in audios:
		if audio['number_of_audio_files'] > 0:
			continue
		else:
			requests.post('http://soundoftext.com/sounds', data={'text':audio['chinese_word'], 'lang':'de'}) # warn the server of what file I'm going to need
			temp_file = download_audio('http://soundoftext.com/static/sounds/de/' + quote(audio['chinese_word'].replace(' ', '_'), safe='') + '.mp3') #download audio file
			if isinstance(temp_file, str):
				print(audio['chinese_word'] + ' skipped: ' + temp_file)
				continue
			else:
				upload_file_to_server(audio['thing_id'], audio['column_number_of_audio'], course_database_url, temp_file)
				temp_file.close()
				print(audio['chinese_word'] + ' succeeded')
```

`
But it also didn't helped.
I'm guessing  the server didn't get this piece when I try to upload audio or sentence with symbols.

`requests.post('http://soundoftext.com/sounds', data={'text':audio['chinese_word'], 'lang':'de'}) # warn the server of what file I'm going to need`

I'm new to programming so I would really appreciate if you can help me with this.
Thank you

**Comment by DrewSSP** [comment]
Hello, and welcome to programming.

I might be able to help you a bit. It looks like the issue is in the format that is being used to send form data to the server. When data is posted to the server the stuff is sent using something like HTML encoding. So, sending
`text:Hello, you are @ the _mall_ :)
lang:en`
would actually look more like
`text=Hello%2C+you+are+%40+the+_mall_+%3A%29&lang=en`
Look at how the spaces get turned into plus signs. This looks a lot like HTML encoding though I don't think HTML encoding typically replaces spaces with plus signs. This might help you fix your problem http://stackoverflow.com/questions/10993692/python-convert-to-html-special-characters. This resource might not process space properly so beware of that.
